# Generated by Django 4.2.1 on 2023-05-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('description', models.TextField(max_length=150)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('salary_type', models.CharField(default='Yearly', max_length=10)),
                ('salary_min', models.CharField(max_length=10)),
                ('salary_max', models.CharField(max_length=10)),
                ('location', models.TextField(max_length=150)),
            ],
        ),
    ]
