# Generated by Django 4.2.1 on 2023-06-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='career_level',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='industry',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='qualification',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
