# Generated by Django 4.2.1 on 2023-06-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_job_career_level_job_experience_job_industry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='profile_pic',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
