# Generated by Django 4.2.2 on 2023-06-24 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='frame',
            new_name='District',
        ),
    ]
