# Generated by Django 4.2.2 on 2023-07-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_choice_district_question_delete_frame_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date published'),
        ),
    ]
