# Generated by Django 4.2.2 on 2023-07-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_district_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='date published'),
        ),
    ]
