# Generated by Django 4.1.7 on 2023-03-21 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_worker_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
    ]
