# Generated by Django 4.1.7 on 2023-04-25 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_workercategory_rename_is_user_login_is_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='appoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.bookappointment'),
        ),
    ]
