# Generated by Django 4.1.7 on 2023-04-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_bill_appoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_num', models.IntegerField(max_length=16)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('cvv', models.IntegerField(max_length=3)),
            ],
        ),
    ]
