# Generated by Django 4.1.7 on 2023-03-24 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_worker_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_pic',
            field=models.FileField(default=1, upload_to='documents/'),
            preserve_default=False,
        ),
    ]
