# Generated by Django 4.1.7 on 2023-04-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
