# Generated by Django 4.1.7 on 2023-03-24 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_customer_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='is_user',
            new_name='is_customer',
        ),
    ]
