# Generated by Django 4.1.7 on 2023-04-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_bill_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookappointment',
            name='completed',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
