# Generated by Django 4.1.7 on 2023-04-08 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_workercategory_worker_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
