# Generated by Django 4.1.7 on 2023-04-12 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_workschedule_remove_worker_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workschedule',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
