# Generated by Django 4.1.7 on 2023-04-18 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_workschedule_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='workschedule',
            name='customer',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
