# Generated by Django 4.1.7 on 2023-04-20 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_bookappointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookappointment',
            old_name='customer',
            new_name='worker',
        ),
    ]
